"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { mediaQueries } from '@/components/css/breakpoint'
import { ThemeProvider } from 'styled-components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Qubly',
  description: 'Generated by create next app',
}

const theme = {
  breakpoints: {
    // xs: "576px",
    // sm: "768px",
    // md: "992px",
    // lg: "1199.99px",
    // xl: "1200px",
    // xxl: "1400px",
    xs: "575.98px",
    sm: "767.98px",
    md: "991.98px",
    lg: "1199.98px",
    xl: "1200px",
  },
  mediaQueries
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='relative'>
          <ThemeProvider theme={theme}>
            {children}
          </ThemeProvider>
        </div>
      </body>
    </html>
  )
}
